### PR TITLE
Update to Swift 5.0

### PR DESCRIPTION
**Pull request by iwb-mohamed-louli**
This PR contains necessary changes for Swift 5/Xcode 10.2 support.

### CODE REVIEW

**Comment by pchelnikov** [comment]
Hi. Sorry for the late response. I'll check this PR next week.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iwb-mohamed-louli** [comment]
Hi, no problem you can check it any time 😅

On 5 May 2019, at 17:07, Michael Pchelnikov <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi. Sorry for the late response. I'll check this PR next week.

Sent with GitHawk<http://githawk.com/>

**Comment by pchelnikov** [comment]
@iwb-mohamed-louli hi again.

Thank you for your PR but I disagree with some code styling. Also, need some work there.

I've updated the repo and released v1.2.0.

**Comment by iwb-mohamed-louli** [comment]
@pchelnikov No problem 😜, thank you for updating the repo and releasing a new version

**Pull request closed without merging**
